In [1]:
import numpy as np

In [2]:
my_list=[[1,2,3],[4,5,6],[3,7,9]]

In [3]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 7, 9]])

numpy built in methods:

1. arange
2. zeros and ones
3. linspace
4. eye

In [4]:
#arange function

In [5]:
# to create an array range we use arange function
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [7]:
#zeros
#if we want to create a matrix or array of 0's
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#ones function will create a matrix with only ones
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones([4,2])/2

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [14]:
#linspance
np.linspace(0,10,5)
#it will create an array of 5 element and its liner means the element will increase by a constant number

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [16]:
#identity
#it will create a identity matrix(equal rows and column)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random module
1. rand
2. randn
3. randint

In [17]:
# rand function  uniform distribution(0,1)
np.random.rand(4)

array([0.62075342, 0.99358154, 0.53538994, 0.43472486])

In [18]:
#lets create a matrix of uniform dist. values
np.random.rand(3,4)

array([[3.86338501e-01, 5.76276575e-01, 1.74678974e-03, 2.81784775e-01],
       [9.54915776e-01, 7.84949447e-01, 3.31302302e-05, 8.89472525e-01],
       [5.20493087e-01, 2.49707887e-01, 8.65905220e-01, 1.22521408e-01]])

In [19]:
#randn - random  standard normal distribution(-3,3)

In [21]:
np.random.randn(3)

array([-0.93859293, -0.54563129, -2.97753729])

In [22]:
np.random.randn(3,4)

array([[ 1.33867736, -0.29242717, -0.62879772,  0.32142377],
       [-0.20929865, -0.06982773,  1.99732426,  0.18667033],
       [-1.79659444,  0.19217996, -0.16430764,  0.05012397]])

In [23]:
#randint : it will give a random integer from range of values for example in range(1,100) it could give 1 but cant give 100 as
#last value is always excluded
np.random.randint(2,100)

11

In [24]:
#if i am looking for more than 1 value
np.random.randint(2,100,6)

array([33, 13, 33, 31, 29, 44])

# various attribute and methods

1. reshape
2. shape
3. max,min,argmax,argmin

In [25]:
x=np.random.randint(1,100,10)

In [26]:
x

array([74, 72, 67, 31, 97, 15, 34, 13, 51, 38])

In [28]:
y=x.reshape(5,2)

In [29]:
y

array([[74, 72],
       [67, 31],
       [97, 15],
       [34, 13],
       [51, 38]])

In [32]:
y.shape

(5, 2)

In [33]:
x.max()

97

In [34]:
x.min()

13

In [36]:
#at which index the max value occur
x.argmax()

4

In [37]:
y.argmax()

4

 **indexing and selection**

1. within a single vector
2. in case of 2D array
3. Selection that is filtring out results

In [38]:
new_array=np.arange(5,20)

In [39]:
new_array


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
#indexing
new_array[3]

8

In [41]:
new_array[0:4]

array([5, 6, 7, 8])

In [42]:
# if we want to change a value in list we can only change one value at a time
my_list=[0,1,2,3,4,5,6,7,8]

In [43]:
my_list[1]=10

In [44]:
my_list

[0, 10, 2, 3, 4, 5, 6, 7, 8]

In [45]:
#but with numpy we can change a range of value at one time
new_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
new_array[0:6]=20

In [47]:
new_array

array([20, 20, 20, 20, 20, 20, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
new_array[5:8]=[10,20,30]

In [49]:
new_array

array([20, 20, 20, 20, 20, 10, 20, 30, 13, 14, 15, 16, 17, 18, 19])

In [50]:
#creating a copy
new_array_v2=new_array.copy()

In [51]:
new_array_v2

array([20, 20, 20, 20, 20, 10, 20, 30, 13, 14, 15, 16, 17, 18, 19])

In [54]:
#indexing in 2D array
new_array=np.array([[1,2,3],[5,6,7],[6,8,9]])

In [55]:
new_array

array([[1, 2, 3],
       [5, 6, 7],
       [6, 8, 9]])

In [57]:
new_array[0]

array([1, 2, 3])

In [58]:
new_array[0][2]

3

In [59]:
#another method using row, column
#new_array[row index,column index]
new_array[1,2]

7

In [60]:
new_array[0:2]

array([[1, 2, 3],
       [5, 6, 7]])

In [61]:
new_array[:2,1:]
#if i want to extract 2 column and 3rd column

array([[2, 3],
       [6, 7]])

In [64]:
new_array[:2,0:2]

array([[1, 2],
       [5, 6]])

# Mathematics

In [65]:
np.sqrt(new_array)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131],
       [2.44948974, 2.82842712, 3.        ]])

In [66]:
np.log(new_array)

array([[0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.79175947, 1.94591015],
       [1.79175947, 2.07944154, 2.19722458]])

In [67]:
np.exp(new_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [4.03428793e+02, 2.98095799e+03, 8.10308393e+03]])